### ISSUE TITLE
YAML as job script format

### ISSUE THREAD

**Issue by dshlai** [KKBOX/mass#1]
I would like to use YAML as another alternative job script format, mostly for its readability. Is it as simple as change json.loads() to yaml.loads()?

**Comment by drakeguan** [comment]
The quick reply is: No.

There are two total different roles of job scripts. The first one is the external interface to users and developers. Right now, there are job scripts in JSON, Alfscript and Pythonic functions. The second one is the internal format used in implemented SWF decider. And it is also in JSON format. Actually, this JSON format is coincidentally the same to the external JSON format.

I guess you are thinking to have a external job script format in YAML. Am I right?

**Comment by dshlai** [comment]
> I guess you are thinking to have a external job script format in YAML. Am I right?

Correct. I was not aware that the job scripts can also function as a format for SWF decider. It will be interesting to see how and why it was implement the way it is. 

BTW, Do you need to write your own parser for alfscript? Or is there already some existing implementation from Pixar? 

Ansible uses YAML as the format for their playbooks, so there are precedence using YAML as a format to declare task.

**Comment by drakeguan** [comment]
The code is already in here and you can check it by yourself :)
